services:
  - type: web
    name: personal-finance-api
    env: docker
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres?user=postgres.regvlqvvqzrcfhyfqgce&sslmode=require
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: DB_USERNAME
        value: postgres.regvlqvvqzrcfhyfqgce
      - key: DB_PASSWORD
        sync: false
