services:
  - type: web
    name: personal-finance-api
    env: docker
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://db.regvlqvvqzrcfhyfqgce.supabase.co:5432/postgres
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
